"""initial

Revision ID: 0001
Revises:
Create Date: 2026-10-02 09:48:53.061528
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

APPEND_ONLY_TABLES = ("ledger_entries", "order_events", "audit_log")

APPEND_ONLY_FN = """
CREATE FUNCTION forbid_change() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION '% is append-only: % is not allowed', TG_TABLE_NAME, TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$
"""

# Frozen copy of the seed (services.settings.DEFAULTS at the time of this migration), so later
# code changes never alter what this migration does.
SETTINGS_SEED = [
    {"key": "commission_bp", "value": 1000},
    {"key": "service_fee", "value": 20},
    {"key": "rider_fee", "value": 100},
    {"key": "unpaid_expiry_minutes", "value": 20},
    {"key": "late_payment_grace_hours", "value": 24},
    {"key": "acceptance_alert_minutes", "value": 5},
    {"key": "acceptance_timeout_minutes", "value": 10},
    {"key": "first_time_cash_cap", "value": 1000},
    {"key": "hotel_unpaid_limit", "value": 5000},
    {"key": "hotel_overdue_days", "value": 3},
    {"key": "rider_compensation_weekly_cap", "value": 2},
    {"key": "order_cutoff_minutes", "value": 15},
    {"key": "rider_payout_default", "value": "instant"},
    {"key": "delivery_zone", "value": []},
    {"key": "_reviewed", "value": False},
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("phone", sa.String(length=12), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("completed_orders", sa.Integer(), server_default="0", nullable=False),
        sa.Column("option_b_blocked", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("blocklisted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("trusted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("last_order_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("phone", name=op.f("pk_customers")),
    )
    op.create_table(
        "hotels",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("phone", sa.String(length=12), nullable=False),
        sa.Column("till_number", sa.String(length=20), nullable=False),
        sa.Column("commission_bp", sa.Integer(), nullable=True),
        sa.Column("service_fee", sa.Integer(), nullable=True),
        sa.Column("cash_pickup_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("accepting_orders", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column("pause_reason", sa.String(length=200), nullable=True),
        sa.Column("cover_image_key", sa.String(length=200), nullable=True),
        sa.Column("accent_color", sa.String(length=7), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('active', 'paused')", name=op.f("ck_hotels_status")),
        sa.CheckConstraint(
            "commission_bp IS NULL OR commission_bp BETWEEN 0 AND 5000",
            name=op.f("ck_hotels_commission_bp_range"),
        ),
        sa.CheckConstraint(
            "service_fee IS NULL OR service_fee >= 0",
            name=op.f("ck_hotels_service_fee_non_negative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hotels")),
        sa.UniqueConstraint("slug", name=op.f("uq_hotels_slug")),
        sa.UniqueConstraint("till_number", name=op.f("uq_hotels_till_number")),
    )
    op.create_table(
        "job_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("job_name", sa.String(length=60), nullable=False),
        sa.Column("period_key", sa.String(length=40), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_runs")),
        sa.UniqueConstraint("job_name", "period_key", name=op.f("uq_job_runs_job_name")),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("hotel_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("available_from", sa.Time(), nullable=True),
        sa.Column("available_to", sa.Time(), nullable=True),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name=op.f("fk_categories_hotel_id_hotels")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("hotel_id", "name", name=op.f("uq_categories_hotel_id")),
    )
    op.create_index(op.f("ix_categories_hotel_id"), "categories", ["hotel_id"], unique=False)
    op.create_table(
        "forwarder_devices",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("hotel_id", sa.UUID(), nullable=True),
        sa.Column("label", sa.String(length=80), nullable=False),
        sa.Column("till_number", sa.String(length=20), nullable=False),
        sa.Column("sim_slot", sa.SmallInteger(), nullable=True),
        sa.Column("secret_encrypted", sa.String(length=300), nullable=False),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name=op.f("fk_forwarder_devices_hotel_id_hotels")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forwarder_devices")),
    )
    op.create_index(
        "uq_forwarder_devices_till_number_active",
        "forwarder_devices",
        ["till_number"],
        unique=True,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_table(
        "hotel_hours",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("hotel_id", sa.UUID(), nullable=False),
        sa.Column("weekday", sa.SmallInteger(), nullable=False),
        sa.Column("opens_at", sa.Time(), nullable=False),
        sa.Column("closes_at", sa.Time(), nullable=False),
        sa.CheckConstraint("weekday BETWEEN 0 AND 6", name=op.f("ck_hotel_hours_weekday_range")),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
            name=op.f("fk_hotel_hours_hotel_id_hotels"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hotel_hours")),
        sa.UniqueConstraint("hotel_id", "weekday", name=op.f("uq_hotel_hours_hotel_id")),
    )
    op.create_table(
        "statements",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("hotel_id", sa.UUID(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("commission_total", sa.Integer(), nullable=False),
        sa.Column("service_fee_total", sa.Integer(), nullable=False),
        sa.Column("rider_fees_held", sa.Integer(), nullable=False),
        sa.Column("amount_due", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=8), server_default="open", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('open', 'paid', 'overdue')", name=op.f("ck_statements_status")
        ),
        sa.CheckConstraint("amount_due >= 0", name=op.f("ck_statements_amount_due_non_negative")),
        sa.CheckConstraint(
            "commission_total >= 0", name=op.f("ck_statements_commission_total_non_negative")
        ),
        sa.CheckConstraint(
            "rider_fees_held >= 0", name=op.f("ck_statements_rider_fees_held_non_negative")
        ),
        sa.CheckConstraint(
            "service_fee_total >= 0", name=op.f("ck_statements_service_fee_total_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name=op.f("fk_statements_hotel_id_hotels")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_statements")),
        sa.UniqueConstraint("hotel_id", "week_start", name=op.f("uq_statements_hotel_id")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("hotel_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=12), nullable=False),
        sa.Column("password_hash", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(role IN ('hotel_admin', 'cashier')) = (hotel_id IS NOT NULL)",
            name=op.f("ck_users_hotel_id_iff_hotel_role"),
        ),
        sa.CheckConstraint(
            "role IN ('super_admin', 'hotel_admin', 'cashier', 'rider')", name=op.f("ck_users_role")
        ),
        sa.ForeignKeyConstraint(["hotel_id"], ["hotels.id"], name=op.f("fk_users_hotel_id_hotels")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("phone", name=op.f("uq_users_phone")),
    )
    op.create_index(op.f("ix_users_hotel_id"), "users", ["hotel_id"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("target_type", sa.String(length=40), nullable=False),
        sa.Column("target_id", sa.String(length=80), nullable=True),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_log_actor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_table(
        "device_nonces",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("nonce", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["forwarder_devices.id"],
            name=op.f("fk_device_nonces_device_id_forwarder_devices"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_nonces")),
        sa.UniqueConstraint("device_id", "nonce", name=op.f("uq_device_nonces_device_id")),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("hotel_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("prep_minutes", sa.Integer(), server_default="15", nullable=False),
        sa.Column("is_sold_out", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("image_key", sa.String(length=200), nullable=True),
        sa.Column("thumb_key", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("prep_minutes > 0", name=op.f("ck_products_prep_minutes_positive")),
        sa.CheckConstraint("price >= 0", name=op.f("ck_products_price_non_negative")),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name=op.f("fk_products_category_id_categories")
        ),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name=op.f("fk_products_hotel_id_hotels")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_index(op.f("ix_products_category_id"), "products", ["category_id"], unique=False)
    op.create_index(op.f("ix_products_hotel_id"), "products", ["hotel_id"], unique=False)
    op.create_table(
        "push_subscriptions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("endpoint", sa.String(length=1000), nullable=False),
        sa.Column("keys", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_push_subscriptions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_push_subscriptions")),
        sa.UniqueConstraint("endpoint", name=op.f("uq_push_subscriptions_endpoint")),
    )
    op.create_index(
        op.f("ix_push_subscriptions_user_id"), "push_subscriptions", ["user_id"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "rider_payouts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("rider_id", sa.UUID(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("mpesa_code", sa.String(length=12), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_rider_payouts_amount_positive")),
        sa.ForeignKeyConstraint(
            ["recorded_by"], ["users.id"], name=op.f("fk_rider_payouts_recorded_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["rider_id"], ["users.id"], name=op.f("fk_rider_payouts_rider_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rider_payouts")),
        sa.UniqueConstraint("mpesa_code", name=op.f("uq_rider_payouts_mpesa_code")),
        sa.UniqueConstraint("rider_id", "period_start", name=op.f("uq_rider_payouts_rider_id")),
    )
    op.create_table(
        "rider_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("national_id", sa.String(length=20), nullable=False),
        sa.Column("mpesa_number", sa.String(length=12), nullable=False),
        sa.Column("next_of_kin", sa.String(length=200), nullable=False),
        sa.Column("payout_mode", sa.String(length=8), server_default="instant", nullable=False),
        sa.Column("is_online", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "payout_mode IN ('instant', 'weekly')", name=op.f("ck_rider_profiles_payout_mode")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_rider_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_rider_profiles")),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_settings_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "settlements",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("hotel_id", sa.UUID(), nullable=False),
        sa.Column("statement_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("mpesa_code", sa.String(length=12), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_settlements_amount_positive")),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name=op.f("fk_settlements_hotel_id_hotels")
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"], ["users.id"], name=op.f("fk_settlements_recorded_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"], ["statements.id"], name=op.f("fk_settlements_statement_id_statements")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settlements")),
        sa.UniqueConstraint("mpesa_code", name=op.f("uq_settlements_mpesa_code")),
    )
    op.create_index(op.f("ix_settlements_hotel_id"), "settlements", ["hotel_id"], unique=False)
    op.create_table(
        "sms_messages",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.String(length=64), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("parse_status", sa.String(length=10), nullable=False),
        sa.Column("trans_code", sa.String(length=12), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=True),
        sa.Column("sender_name", sa.String(length=120), nullable=True),
        sa.Column("phone_digits", sa.String(length=16), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "parse_status IN ('parsed', 'failed', 'reversal', 'ignored')",
            name=op.f("ck_sms_messages_parse_status"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["forwarder_devices.id"],
            name=op.f("fk_sms_messages_device_id_forwarder_devices"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_messages")),
        sa.UniqueConstraint("message_id", name=op.f("uq_sms_messages_message_id")),
    )
    op.create_index(op.f("ix_sms_messages_device_id"), "sms_messages", ["device_id"], unique=False)
    op.create_index(
        op.f("ix_sms_messages_trans_code"), "sms_messages", ["trans_code"], unique=False
    )
    op.create_table(
        "discounts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("hotel_id", sa.UUID(), nullable=False),
        sa.Column("scope", sa.String(length=8), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("min_spend", sa.Integer(), server_default="0", nullable=False),
        sa.Column("promo_code", sa.String(length=32), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope = 'item') = (product_id IS NOT NULL)",
            name=op.f("ck_discounts_product_iff_item"),
        ),
        sa.CheckConstraint(
            "kind <> 'percent' OR value <= 10000", name=op.f("ck_discounts_percent_max_100")
        ),
        sa.CheckConstraint("kind IN ('percent', 'fixed')", name=op.f("ck_discounts_kind")),
        sa.CheckConstraint("scope IN ('item', 'order')", name=op.f("ck_discounts_scope")),
        sa.CheckConstraint(
            "ends_at IS NULL OR ends_at > starts_at", name=op.f("ck_discounts_ends_after_starts")
        ),
        sa.CheckConstraint(
            "max_uses IS NULL OR max_uses > 0", name=op.f("ck_discounts_max_uses_positive")
        ),
        sa.CheckConstraint("min_spend >= 0", name=op.f("ck_discounts_min_spend_non_negative")),
        sa.CheckConstraint("value > 0", name=op.f("ck_discounts_value_positive")),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name=op.f("fk_discounts_hotel_id_hotels")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_discounts_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discounts")),
    )
    op.create_index(op.f("ix_discounts_hotel_id"), "discounts", ["hotel_id"], unique=False)
    op.create_index(
        "uq_discounts_hotel_id_promo_code",
        "discounts",
        ["hotel_id", "promo_code"],
        unique=True,
        postgresql_where=sa.text("promo_code IS NOT NULL"),
    )
    op.create_table(
        "product_options",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("group_name", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("price_delta", sa.Integer(), server_default="0", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
        sa.CheckConstraint(
            "price_delta >= 0", name=op.f("ck_product_options_price_delta_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_product_options_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_options")),
    )
    op.create_index(
        op.f("ix_product_options_product_id"), "product_options", ["product_id"], unique=False
    )
    op.create_table(
        "offers",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("hotel_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("image_key", sa.String(length=200), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("discount_id", sa.UUID(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["discount_id"], ["discounts.id"], name=op.f("fk_offers_discount_id_discounts")
        ),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name=op.f("fk_offers_hotel_id_hotels")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_offers_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offers")),
    )
    op.create_index(op.f("ix_offers_hotel_id"), "offers", ["hotel_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("tracking_token", sa.String(length=64), nullable=False),
        sa.Column("hotel_id", sa.UUID(), nullable=False),
        sa.Column("customer_phone", sa.String(length=12), nullable=False),
        sa.Column("customer_name", sa.String(length=120), nullable=False),
        sa.Column("type", sa.String(length=8), nullable=False),
        sa.Column("rider_fee_mode", sa.String(length=8), nullable=False),
        sa.Column("payment_method", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.Column("landmark", sa.String(length=300), nullable=True),
        sa.Column("items_total", sa.Integer(), nullable=False),
        sa.Column("order_discount", sa.Integer(), nullable=False),
        sa.Column("food_net", sa.Integer(), nullable=False),
        sa.Column("service_fee", sa.Integer(), nullable=False),
        sa.Column("rider_fee", sa.Integer(), nullable=False),
        sa.Column("rider_fee_in_till", sa.Integer(), nullable=False),
        sa.Column("till_amount", sa.Integer(), nullable=False),
        sa.Column("commission_bp", sa.Integer(), nullable=False),
        sa.Column("commission_amount", sa.Integer(), nullable=False),
        sa.Column("discount_id", sa.UUID(), nullable=True),
        sa.Column("customer_trans_code", sa.String(length=12), nullable=True),
        sa.Column("delivery_code", sa.String(length=4), nullable=True),
        sa.Column("rider_id", sa.UUID(), nullable=True),
        sa.Column("prep_minutes", sa.Integer(), nullable=True),
        sa.Column("reason", sa.String(length=300), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("preparing_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("picked_up_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("on_the_way_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(rider_fee_mode = 'included' AND rider_fee_in_till = rider_fee) OR (rider_fee_mode <> 'included' AND rider_fee_in_till = 0)",
            name=op.f("ck_orders_rider_fee_in_till_by_mode"),
        ),
        sa.CheckConstraint(
            "(type = 'pickup' AND rider_fee_mode = 'none' AND rider_fee = 0) OR (type = 'delivery' AND rider_fee_mode IN ('included', 'cash') AND payment_method = 'mpesa' AND lat IS NOT NULL AND lng IS NOT NULL)",
            name=op.f("ck_orders_type_rules"),
        ),
        sa.CheckConstraint(
            "payment_method IN ('mpesa', 'cash')", name=op.f("ck_orders_payment_method")
        ),
        sa.CheckConstraint(
            "rider_fee_mode IN ('included', 'cash', 'none')", name=op.f("ck_orders_rider_fee_mode")
        ),
        sa.CheckConstraint(
            "status IN ('awaiting_payment', 'checking_payment', 'paid', 'accepted', 'preparing', 'ready', 'picked_up', 'on_the_way', 'delivered', 'collected', 'expired', 'rejected', 'cancelled', 'failed_delivery')",
            name=op.f("ck_orders_status"),
        ),
        sa.CheckConstraint("type IN ('delivery', 'pickup')", name=op.f("ck_orders_type")),
        sa.CheckConstraint(
            "commission_amount <= food_net", name=op.f("ck_orders_commission_within_food")
        ),
        sa.CheckConstraint(
            "commission_amount >= 0", name=op.f("ck_orders_commission_amount_non_negative")
        ),
        sa.CheckConstraint(
            "commission_bp BETWEEN 0 AND 10000", name=op.f("ck_orders_commission_bp_range")
        ),
        sa.CheckConstraint(
            "food_net = items_total - order_discount", name=op.f("ck_orders_food_net_sum")
        ),
        sa.CheckConstraint("food_net >= 0", name=op.f("ck_orders_food_net_non_negative")),
        sa.CheckConstraint("items_total >= 0", name=op.f("ck_orders_items_total_non_negative")),
        sa.CheckConstraint(
            "order_discount >= 0", name=op.f("ck_orders_order_discount_non_negative")
        ),
        sa.CheckConstraint("rider_fee >= 0", name=op.f("ck_orders_rider_fee_non_negative")),
        sa.CheckConstraint(
            "rider_fee_in_till >= 0", name=op.f("ck_orders_rider_fee_in_till_non_negative")
        ),
        sa.CheckConstraint("service_fee >= 0", name=op.f("ck_orders_service_fee_non_negative")),
        sa.CheckConstraint(
            "till_amount = food_net + service_fee + rider_fee_in_till",
            name=op.f("ck_orders_till_amount_sum"),
        ),
        sa.CheckConstraint("till_amount >= 0", name=op.f("ck_orders_till_amount_non_negative")),
        sa.ForeignKeyConstraint(
            ["customer_phone"], ["customers.phone"], name=op.f("fk_orders_customer_phone_customers")
        ),
        sa.ForeignKeyConstraint(
            ["discount_id"], ["discounts.id"], name=op.f("fk_orders_discount_id_discounts")
        ),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name=op.f("fk_orders_hotel_id_hotels")
        ),
        sa.ForeignKeyConstraint(["rider_id"], ["users.id"], name=op.f("fk_orders_rider_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("code", name=op.f("uq_orders_code")),
        sa.UniqueConstraint("tracking_token", name=op.f("uq_orders_tracking_token")),
    )
    op.create_index(op.f("ix_orders_customer_phone"), "orders", ["customer_phone"], unique=False)
    op.create_index(
        "ix_orders_hotel_status_created",
        "orders",
        ["hotel_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_orders_rider_id"), "orders", ["rider_id"], unique=False)
    op.create_table(
        "idempotency_keys",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_idempotency_keys_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_idempotency_keys")),
    )
    op.create_index(
        op.f("ix_idempotency_keys_expires_at"), "idempotency_keys", ["expires_at"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("event", sa.String(length=40), nullable=False),
        sa.Column("channel", sa.String(length=8), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("channel IN ('sms', 'push')", name=op.f("ck_notifications_channel")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_notifications_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint("order_id", "event", "channel", name=op.f("uq_notifications_order_id")),
    )
    op.create_table(
        "order_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("from_status", sa.String(length=20), nullable=True),
        sa.Column("to_status", sa.String(length=20), nullable=False),
        sa.Column("actor_type", sa.String(length=12), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_type IN ('customer', 'staff', 'rider', 'admin', 'system', 'forwarder')",
            name=op.f("ck_order_events_actor_type"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_events_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_events")),
    )
    op.create_index(op.f("ix_order_events_order_id"), "order_events", ["order_id"], unique=False)
    op.create_table(
        "order_items",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("name_snapshot", sa.String(length=120), nullable=False),
        sa.Column("unit_price", sa.Integer(), nullable=False),
        sa.Column(
            "options_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("options_price", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("line_discount", sa.Integer(), nullable=False),
        sa.Column("line_total", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "line_discount >= 0", name=op.f("ck_order_items_line_discount_non_negative")
        ),
        sa.CheckConstraint(
            "line_total = (unit_price + options_price) * quantity - line_discount",
            name=op.f("ck_order_items_line_total_sum"),
        ),
        sa.CheckConstraint("line_total >= 0", name=op.f("ck_order_items_line_total_non_negative")),
        sa.CheckConstraint(
            "options_price >= 0", name=op.f("ck_order_items_options_price_non_negative")
        ),
        sa.CheckConstraint("quantity BETWEEN 1 AND 20", name=op.f("ck_order_items_quantity_range")),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_order_items_unit_price_non_negative")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_order_items_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
    )
    op.create_index(op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("till_number", sa.String(length=20), nullable=False),
        sa.Column("trans_code", sa.String(length=12), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("sms_message_id", sa.UUID(), nullable=True),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("settlement_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("confirmed_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('forwarder', 'manual', 'daraja')", name=op.f("ck_payments_source")
        ),
        sa.CheckConstraint(
            "status IN ('matched', 'review', 'reversed')", name=op.f("ck_payments_status")
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payments_amount_positive")),
        sa.ForeignKeyConstraint(
            ["confirmed_by"], ["users.id"], name=op.f("fk_payments_confirmed_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_payments_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["settlement_id"],
            ["settlements.id"],
            name=op.f("fk_payments_settlement_id_settlements"),
        ),
        sa.ForeignKeyConstraint(
            ["sms_message_id"],
            ["sms_messages.id"],
            name=op.f("fk_payments_sms_message_id_sms_messages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("trans_code", name=op.f("uq_payments_trans_code")),
    )
    op.create_index(
        "uq_payments_order_id",
        "payments",
        ["order_id"],
        unique=True,
        postgresql_where=sa.text("order_id IS NOT NULL"),
    )
    op.create_table(
        "promo_redemptions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("discount_id", sa.UUID(), nullable=False),
        sa.Column("phone", sa.String(length=12), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["discount_id"],
            ["discounts.id"],
            name=op.f("fk_promo_redemptions_discount_id_discounts"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_promo_redemptions_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promo_redemptions")),
        sa.UniqueConstraint("discount_id", "phone", name=op.f("uq_promo_redemptions_discount_id")),
    )
    op.create_table(
        "refunds",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("food_amount", sa.Integer(), nullable=False),
        sa.Column("service_fee_amount", sa.Integer(), nullable=False),
        sa.Column("rider_fee_amount", sa.Integer(), nullable=False),
        sa.Column("excess_amount", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=False),
        sa.Column("status", sa.String(length=10), server_default="approved", nullable=False),
        sa.Column("mpesa_code", sa.String(length=12), nullable=True),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("sent_by", sa.UUID(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'sent') = (mpesa_code IS NOT NULL)", name=op.f("ck_refunds_sent_has_code")
        ),
        sa.CheckConstraint("status IN ('approved', 'sent')", name=op.f("ck_refunds_status")),
        sa.CheckConstraint(
            "amount = food_amount + service_fee_amount + rider_fee_amount + excess_amount",
            name=op.f("ck_refunds_parts_sum"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_refunds_amount_positive")),
        sa.CheckConstraint(
            "excess_amount >= 0", name=op.f("ck_refunds_excess_amount_non_negative")
        ),
        sa.CheckConstraint("food_amount >= 0", name=op.f("ck_refunds_food_amount_non_negative")),
        sa.CheckConstraint(
            "rider_fee_amount >= 0", name=op.f("ck_refunds_rider_fee_amount_non_negative")
        ),
        sa.CheckConstraint(
            "service_fee_amount >= 0", name=op.f("ck_refunds_service_fee_amount_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.id"], name=op.f("fk_refunds_approved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_refunds_order_id_orders")
        ),
        sa.ForeignKeyConstraint(["sent_by"], ["users.id"], name=op.f("fk_refunds_sent_by_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refunds")),
    )
    op.create_index(op.f("ix_refunds_order_id"), "refunds", ["order_id"], unique=False)
    op.create_index(
        "uq_refunds_mpesa_code",
        "refunds",
        ["mpesa_code"],
        unique=True,
        postgresql_where=sa.text("mpesa_code IS NOT NULL"),
    )
    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("entry_type", sa.String(length=24), nullable=False),
        sa.Column("kind", sa.String(length=12), nullable=False),
        sa.Column("from_party", sa.String(length=10), nullable=False),
        sa.Column("from_id", sa.Uuid(), nullable=True),
        sa.Column("to_party", sa.String(length=10), nullable=False),
        sa.Column("to_id", sa.Uuid(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("refund_id", sa.UUID(), nullable=True),
        sa.Column("statement_id", sa.UUID(), nullable=True),
        sa.Column("settlement_id", sa.UUID(), nullable=True),
        sa.Column("payout_id", sa.UUID(), nullable=True),
        sa.Column("reference", sa.String(length=64), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entry_type IN ('till_received', 'cash_received', 'commission', 'service_fee', 'commission_reversal', 'service_fee_reversal', 'refund', 'rider_fee_instant', 'rider_fee_held', 'rider_fee_owed', 'rider_fee_cash', 'rider_compensation', 'settlement', 'rider_payout')",
            name=op.f("ck_ledger_entries_entry_type"),
        ),
        sa.CheckConstraint(
            "from_party IN ('platform', 'hotel', 'rider', 'customer')",
            name=op.f("ck_ledger_entries_from_party"),
        ),
        sa.CheckConstraint(
            "kind IN ('obligation', 'payment')", name=op.f("ck_ledger_entries_kind")
        ),
        sa.CheckConstraint(
            "to_party IN ('platform', 'hotel', 'rider', 'customer')",
            name=op.f("ck_ledger_entries_to_party"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_ledger_entries_amount_positive")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_ledger_entries_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_ledger_entries_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["payout_id"],
            ["rider_payouts.id"],
            name=op.f("fk_ledger_entries_payout_id_rider_payouts"),
        ),
        sa.ForeignKeyConstraint(
            ["refund_id"], ["refunds.id"], name=op.f("fk_ledger_entries_refund_id_refunds")
        ),
        sa.ForeignKeyConstraint(
            ["settlement_id"],
            ["settlements.id"],
            name=op.f("fk_ledger_entries_settlement_id_settlements"),
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["statements.id"],
            name=op.f("fk_ledger_entries_statement_id_statements"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_entries")),
    )
    op.create_index(
        op.f("ix_ledger_entries_order_id"), "ledger_entries", ["order_id"], unique=False
    )
    op.create_index("ix_ledger_from", "ledger_entries", ["from_party", "from_id"], unique=False)
    op.create_index("ix_ledger_to", "ledger_entries", ["to_party", "to_id"], unique=False)
    op.create_index(
        "uq_ledger_order_entry",
        "ledger_entries",
        ["order_id", "entry_type"],
        unique=True,
        postgresql_where=sa.text("order_id IS NOT NULL AND refund_id IS NULL"),
    )
    op.create_index(
        "uq_ledger_payout_entry",
        "ledger_entries",
        ["payout_id", "entry_type"],
        unique=True,
        postgresql_where=sa.text("payout_id IS NOT NULL"),
    )
    op.create_index(
        "uq_ledger_refund_entry",
        "ledger_entries",
        ["refund_id", "entry_type"],
        unique=True,
        postgresql_where=sa.text("refund_id IS NOT NULL"),
    )
    op.create_index(
        "uq_ledger_settlement_entry",
        "ledger_entries",
        ["settlement_id", "entry_type"],
        unique=True,
        postgresql_where=sa.text("settlement_id IS NOT NULL"),
    )
    op.create_index(
        "uq_ledger_statement_entry",
        "ledger_entries",
        ["statement_id", "entry_type"],
        unique=True,
        postgresql_where=sa.text("statement_id IS NOT NULL"),
    )
    op.create_table(
        "review_items",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("hotel_id", sa.UUID(), nullable=True),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("payment_id", sa.UUID(), nullable=True),
        sa.Column("sms_message_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.String(length=300), nullable=False),
        sa.Column("status", sa.String(length=10), server_default="open", nullable=False),
        sa.Column("resolution", sa.String(length=300), nullable=True),
        sa.Column("resolved_by", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('open', 'resolved')", name=op.f("ck_review_items_status")),
        sa.CheckConstraint(
            "type IN ('underpaid', 'overpaid', 'unmatched_sms', 'no_sms', 'reversal', 'parse_failed', 'late_payment', 'fee_dispute', 'failed_delivery')",
            name=op.f("ck_review_items_type"),
        ),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name=op.f("fk_review_items_hotel_id_hotels")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_review_items_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"], ["payments.id"], name=op.f("fk_review_items_payment_id_payments")
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"], ["users.id"], name=op.f("fk_review_items_resolved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["sms_message_id"],
            ["sms_messages.id"],
            name=op.f("fk_review_items_sms_message_id_sms_messages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_items")),
    )
    op.create_index(
        "ix_review_items_hotel_status", "review_items", ["hotel_id", "status"], unique=False
    )
    # ### end Alembic commands ###

    # Append-only tables: money and audit records are never edited or deleted.
    op.execute(APPEND_ONLY_FN)
    for table in APPEND_ONLY_TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION forbid_change()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION forbid_change()"
        )

    # D1: seed settings with the spec's proposed defaults, marked unreviewed.
    settings_table = sa.table(
        "settings", sa.column("key", sa.String), sa.column("value", postgresql.JSONB)
    )
    op.bulk_insert(settings_table, SETTINGS_SEED)


def downgrade() -> None:
    for table in APPEND_ONLY_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_truncate ON {table}")
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}")
    op.execute("DROP FUNCTION IF EXISTS forbid_change()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_review_items_hotel_status", table_name="review_items")
    op.drop_table("review_items")
    op.drop_index(
        "uq_ledger_statement_entry",
        table_name="ledger_entries",
        postgresql_where=sa.text("statement_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_ledger_settlement_entry",
        table_name="ledger_entries",
        postgresql_where=sa.text("settlement_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_ledger_refund_entry",
        table_name="ledger_entries",
        postgresql_where=sa.text("refund_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_ledger_payout_entry",
        table_name="ledger_entries",
        postgresql_where=sa.text("payout_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_ledger_order_entry",
        table_name="ledger_entries",
        postgresql_where=sa.text("order_id IS NOT NULL AND refund_id IS NULL"),
    )
    op.drop_index("ix_ledger_to", table_name="ledger_entries")
    op.drop_index("ix_ledger_from", table_name="ledger_entries")
    op.drop_index(op.f("ix_ledger_entries_order_id"), table_name="ledger_entries")
    op.drop_table("ledger_entries")
    op.drop_index(
        "uq_refunds_mpesa_code",
        table_name="refunds",
        postgresql_where=sa.text("mpesa_code IS NOT NULL"),
    )
    op.drop_index(op.f("ix_refunds_order_id"), table_name="refunds")
    op.drop_table("refunds")
    op.drop_table("promo_redemptions")
    op.drop_index(
        "uq_payments_order_id",
        table_name="payments",
        postgresql_where=sa.text("order_id IS NOT NULL"),
    )
    op.drop_table("payments")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_order_events_order_id"), table_name="order_events")
    op.drop_table("order_events")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_idempotency_keys_expires_at"), table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_index(op.f("ix_orders_rider_id"), table_name="orders")
    op.drop_index("ix_orders_hotel_status_created", table_name="orders")
    op.drop_index(op.f("ix_orders_customer_phone"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_offers_hotel_id"), table_name="offers")
    op.drop_table("offers")
    op.drop_index(op.f("ix_product_options_product_id"), table_name="product_options")
    op.drop_table("product_options")
    op.drop_index(
        "uq_discounts_hotel_id_promo_code",
        table_name="discounts",
        postgresql_where=sa.text("promo_code IS NOT NULL"),
    )
    op.drop_index(op.f("ix_discounts_hotel_id"), table_name="discounts")
    op.drop_table("discounts")
    op.drop_index(op.f("ix_sms_messages_trans_code"), table_name="sms_messages")
    op.drop_index(op.f("ix_sms_messages_device_id"), table_name="sms_messages")
    op.drop_table("sms_messages")
    op.drop_index(op.f("ix_settlements_hotel_id"), table_name="settlements")
    op.drop_table("settlements")
    op.drop_table("settings")
    op.drop_table("rider_profiles")
    op.drop_table("rider_payouts")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_push_subscriptions_user_id"), table_name="push_subscriptions")
    op.drop_table("push_subscriptions")
    op.drop_index(op.f("ix_products_hotel_id"), table_name="products")
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_table("products")
    op.drop_table("device_nonces")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_users_hotel_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("statements")
    op.drop_table("hotel_hours")
    op.drop_index(
        "uq_forwarder_devices_till_number_active",
        table_name="forwarder_devices",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_table("forwarder_devices")
    op.drop_index(op.f("ix_categories_hotel_id"), table_name="categories")
    op.drop_table("categories")
    op.drop_table("job_runs")
    op.drop_table("hotels")
    op.drop_table("customers")
    # ### end Alembic commands ###
